### ISSUE TITLE
Suggestion about duplicated HomeKitFlasher.exe location

### ISSUE THREAD

**Issue by RavenSystem** [vglucas/HomeKitFlasher#1]
I suggest you to remove HomeKitFlasher.exe file from repository and keep it only under Releases tab, because downloads directly from repository do not up downloads-counter. Repository is thought to use better with source code, instructions, info files, etc...

**Comment by vglucas** [comment]
Thanks for the suggestion, the suggestions are always welcome, done!

**Comment by RavenSystem** [comment]
;)
