### ISSUE TITLE
Remote Server Returned an Error - Not logged in

### ISSUE THREAD

**Issue by paulfj40** [vglucas/HomeKitFlasher#2]
When I try to run the application I get an error:

Err:20- Generic Error -The remote server returned an error: 
(530) Not Logged in. 

Is there something I am doing wrong?

**Comment by vglucas** [comment]
Hi paulfj40, check the internet connection, the program checks the HAA version on the server, it is likely that at this moment you have connection problems, try again and let me know

**Comment by paulfj40** [comment]
Thanks for your fast response vglucas. I did check it and it seems to be fine, I'm actually sending this mail from the computer I am running the application on.

**Comment by vglucas** [comment]
Hi paulfj40 let me know if you have solved, to close the request 😜👍

**Comment by paulfj40** [comment]
Sorry, the internet connection is good, but the error still exists.

**Comment by vglucas** [comment]
the version on the RAVENCORE and HAA key is present ??

**Comment by paulfj40** [comment]
no, it just says version, i have attached a screenshot. I hope that helps.

![image](https://user-images.githubusercontent.com/58269484/69752230-9fb26a00-1105-11ea-98af-9e683bfcfa06.png)

**Comment by vglucas** [comment]
the Ravencore and HAA version is not present so you cannot load it from the server Here is the error.  try to close and reopen the program
![47A0E6FD-38C2-48A1-837E-A9BEC4B9E5E3](https://user-images.githubusercontent.com/49847470/69752752-3442b980-1152-11ea-8a0f-8cf35c1d3abf.jpeg)

**Comment by vglucas** [comment]
![9882FCB5-3567-4E1D-AF8C-EB3A35E74AAA](https://user-images.githubusercontent.com/49847470/69752860-7966eb80-1152-11ea-8f03-6ea448bd91e2.jpeg)

**Comment by paulfj40** [comment]
same error, could it be something in my settings. Do you have the link so I can try and check it?

**Comment by vglucas** [comment]
I do a check and I will contact you in a few minutes 😜👍

**Comment by vglucas** [comment]
in the program there is the section SEGNALA  Send me a report from there

**Comment by paulfj40** [comment]
I have just sent it to you. Thank you again for your help.

**Comment by paulfj40** [comment]
Perfect! Thank you so much. This is such a great app for homekit users who want to flash a device like a sonoff or a Shelly. Thanks for your great support.
