### ISSUE TITLE
Error Message during installation

### ISSUE THREAD

**Issue by peros550** [vglucas/HomeKitFlasher#3]
"The application requires that assembly:
Microsoft.VisualBasic.Powerpacks.Vs Version 10.0.0.0 be installed in the Global Assembly Cache (GAC) first"

Very strangely, it asked me to install this dependency and I pressed Accept.

**Comment by vglucas** [comment]
it's ok, it's an add-on from Microsoft

**Comment by peros550** [comment]
I know, still the program wasn't able to install it. Maybe it's on my side. I will close the issue and if anybody else faces the same will/may reply back.

**Comment by vglucas** [comment]
Install this

https://go.microsoft.com/fwlink/?LinkID=145727&clcid=0x804

Il giorno 16 dic 2019, alle ore 14:55, peros550 <notifications@github.com> ha scritto:

I know, still the program wasn't able to install it. Maybe it's on my side. I will close the issue and if anybody else faces the same will/may reply back.

**Comment by peros550** [comment]
Thanks! 
Perhaps the first issue was on my end. It needed me to run the *.exe as administrator.

It run the clickonce installation and then I got another error message: Python non istallato....
