### ISSUE TITLE
Flash HAA firmware button is not available

### ISSUE THREAD

**Issue by 400HPMustang** [vglucas/HomeKitFlasher#4]
I can connect to my flasher, extract the mac address, and then erase the firmware successfully. However none of the options to flash new firmware are enabled. Please let me know what information I can provide to help resolve this issue. 

I am flashing a Sonoff iFan03 if the device itself matters.

**Comment by vglucas** [comment]
hi you have to click on thumb 👍 to enable the keys, let me know if it is ok


Il giorno 2 mag 2020, alle ore 01:50, 400HPMustang <notifications@github.com> ha scritto:

﻿

I can connect to my flasher, extract the mac address, and then erase the firmware successfully. However none of the options to flash new firmware are enabled. Please let me know what information I can provide to help resolve this issue.

I am flashing a Sonoff iFan03 if the device itself matters.

**Comment by 400HPMustang** [comment]
Hi, yes this worked. The buttons were enabled however only flashing HAA.2.01.00 was successful. Flashing OTA HAA 3.0.2 was not successful. It would be nice if OTA was working. 

Additional note, is it documented somewhere that clicking the thumb is necessary to enable the buttons? If not, please include in your documentation. I was confused for quite a while.

**Comment by vglucas** [comment]
OTA also works great, already tested and working - to enable the keys I include it in the wiki
________________________________
Da: 400HPMustang <notifications@github.com>
Inviato: sabato 2 maggio 2020 18:09
A: vglucas/HomeKitFlasher <HomeKitFlasher@noreply.github.com>
Cc: vglucas <gia.sca@hotmail.it>; State change <state_change@noreply.github.com>
Oggetto: Re: [vglucas/HomeKitFlasher] Flash HAA firmware button is not available (#4)


Hi, yes this worked. The buttons were enabled however only flashing HAA.2.01.00 was successful. Flashing OTA HAA 3.0.2 was not successful. It would be nice if OTA was working.

Additional note, is it documented somewhere that clicking the thumb is necessary to enable the buttons? If not, please include in your documentation. I was confused for quite a while.

**Comment by 400HPMustang** [comment]
I did not have success with OTA.

**Comment by vglucas** [comment]
you can try again?

if it still doesn't work let me know, write from the program in the menu ? and REPORT
________________________________
Da: 400HPMustang <notifications@github.com>
Inviato: sabato 2 maggio 2020 18:18
A: vglucas/HomeKitFlasher <HomeKitFlasher@noreply.github.com>
Cc: vglucas <gia.sca@hotmail.it>; State change <state_change@noreply.github.com>
Oggetto: Re: [vglucas/HomeKitFlasher] Flash HAA firmware button is not available (#4)


I did not have success with OTA.
