### ISSUE TITLE
installed but can't execute

### ISSUE THREAD

**Issue by caiotadashi** [vglucas/HomeKitFlasher#5]
hi! i've installed, the shortcut is on my desktop but when I click the "opening window" open and closes and nothing happens. I can see the process on the task manager but closes itself.

**Comment by vglucas** [comment]
uninstall and reinstall the program

Il giorno 3 giu 2020, alle ore 19:18, caiotadashi <notifications@github.com> ha scritto:


hi! i've installed, the shortcut is on my desktop but when I click the "opening window" open and closes and nothing happens. I can see the process on the task manager but closes itself.

**Comment by caiotadashi** [comment]
already done but still the same

**Comment by vglucas** [comment]
did you send the program from this link??
https://github.com/vglucas/HomeKitFlasher/releases/download/v.1.0/HomeKitFlasher.exe

**Comment by caiotadashi** [comment]
yup! tried to download and reinstall (uninstall and reinstall) again but same behavior.

**Comment by vglucas** [comment]
problem never encountered, have you tried with another pc?

**Comment by caiotadashi** [comment]
I don't have another pc ://
already flashed using the official tool
thank you!
